sudo: required
services:
  - docker

before_install:
  - docker build -t react-boilerplate .

script:
	- docker run react-boilerplate npm run test -- --coverage

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  
  keep_history: true
  on:
    branch: master