sudo: required
services:
  - docker

before_install:
  - docker build -t react-boilerplate .

script:
  - docker run react-boilerplate npm run test -- --coverage

before_deploy:
  - docker run -v $(TRAVIS_BUILD_DIR)/dist:/usr/share/nginx/html react-boilerplate

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  
  keep_history: true
  local_dir: dist
  on:
    branch: master