sudo: required
services:
  - docker

before_install:
  - docker build -t react-boilerplate .

script:
  - docker run react-boilerplate pwd
  - docker run react-boilerplate ls
  - docker run react-boilerplate cp -R /usr/share/nginx/html/ ~/$TRAVIS_BUILD_DIR/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  
  keep_history: true
  on:
    branch: master